story1/urls.py
from django.urls import path

from .views import about

urlpatterns = [
    path('', about, name='about'),
]

story3/urls.py
from django.urls import path

from .views import index, projects

urlpatterns = [
    path('', index, name='index'),
    path('projects', projects, name='projects')
]

story5/urls.py
from django.urls import path, include
from .views import add_course, all_course, view_course, delete_course

urlpatterns = [
    path('add', add_course, name='add-course'),
    path('delete', delete_course, name='delete-course'),
    path('', all_course, name='all-course'),
    path('course/<str:name>', view_course, name='view-course')
]

story6/urls.py
from django.urls import path
from .views import all_kegiatan_view, kegiatan_detail_view, kegiatan_delete_pendaftar, add_kegiatan_view

app_name = "story6"

urlpatterns = [
    path("", all_kegiatan_view, name="all-kegiatan"),
    path("detail/<int:id>", kegiatan_detail_view, name="kegiatan-detail"),
    path("delete/<int:id>", kegiatan_delete_pendaftar, name="pendaftar-delete"),
    path("add", add_kegiatan_view, name="add-kegiatan")
]

storyheroku/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('timey/', include('timey.urls')),
    path('story1/', include('story1.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('', include('story3.urls'))
]

timey/urls.py
from django.urls import path

from .views import time

urlpatterns = [
    path('', time, name='default-time'),
    path('<int:offset>', time, name='time'),
]

story1/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=40, primary_key=True)
    lecturer = models.CharField(max_length=60)
    credit = models.PositiveSmallIntegerField()
    description = models.TextField()
    term = models.CharField(max_length=50)
    room = models.CharField(max_length=50)


class Task(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField()
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name='tasks')
    deadline = models.DateField()

    class Meta:
        ordering = ['-deadline']

story6/models.py
from django.db import models


class Kegiatan(models.Model):
    nama = models.CharField(max_length=100)
    deskripsi = models.TextField()
    tanggal_dibuat = models.DateTimeField(auto_now_add=True)


class Pendaftar(models.Model):
    nama = models.CharField(max_length=70)
    kegiatan = models.ForeignKey(
        Kegiatan, on_delete=models.CASCADE, related_name='pendaftar')

timey/models.py
from django.db import models

# Create your models here.

story5/forms.py
from django.forms import ModelForm, Form, ChoiceField
from .models import Course


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class DeleteCourseForm(Form):
    def __init__(self, matkuls, *args, **kwargs):
        super(DeleteCourseForm, self).__init__(*args, **kwargs)
        self.fields["courses"].choices = matkuls

    courses = ChoiceField(choices=(), required=True, label="Course Name")

story6/forms.py
from django import forms
from .models import Kegiatan, Pendaftar


class TambahPendaftarForm(forms.ModelForm):
    class Meta:
        model = Pendaftar
        fields = "__all__"
        widgets = {
            "kegiatan": forms.HiddenInput()
        }


class TambahKegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = "__all__"

story1/views.py
from django.shortcuts import render

# Create your views here.


def about(req):
    return render(req, "about.html")

story3/views.py
from django.shortcuts import render


def index(req):
    return render(req, "index.html")


def projects(req):
    return render(req, "projects.html")

story5/views.py
from django.shortcuts import render, redirect
from .forms import CourseForm, DeleteCourseForm
from .models import Course, Task
import datetime


def add_course(req):
    courses = [(course.name, course.name) for course in Course.objects.all()]
    if req.method == 'POST':
        form = CourseForm(req.POST)
        if form.is_valid():
            new_course = form.save()
            return redirect('all-course')
    else:
        form = CourseForm()
    delete_form = DeleteCourseForm(courses)
    return render(req, 'story5/addcourse.html', {'form': form, 'delete_form': delete_form})


def delete_course(req):
    courses = [(course.name, course.name) for course in Course.objects.all()]
    if req.method == 'POST':
        delete_form = DeleteCourseForm(courses, req.POST)
        if delete_form.is_valid():
            Course.objects.get(pk=req.POST.get('courses')).delete()
            return redirect('all-course')
    else:
        delete_form = DeleteCourseForm(courses)
    form = CourseForm()
    return render(req, 'story5/addcourse.html', {'form': form, 'delete_form': delete_form})


def all_course(req):
    all_course = Course.objects.all()
    return render(req, 'story5/allcourse.html', {'courses': all_course})


def view_course(req, name):
    course = Course.objects.get(pk=name)
    tasks = course.tasks.all()
    currtime = datetime.datetime.now()
    past_tasks = [t for t in tasks if t.deadline < currtime.date()]
    close_tasks = [t for t in tasks if (
        t.deadline - currtime.date()).days <= 7 and t not in past_tasks]
    tasks = [
        t for t in tasks if t not in past_tasks and t not in close_tasks]
    return render(req, 'story5/course.html', {'course': course, 'tasks': tasks, 'past_tasks': past_tasks, 'close_tasks': close_tasks, 'tasks': tasks})

story6/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from .models import Kegiatan, Pendaftar
from .forms import TambahPendaftarForm, TambahKegiatanForm


def all_kegiatan_view(request):
    kegiatan_all = Kegiatan.objects.all()
    context = {
        "kegiatan_all": kegiatan_all
    }
    return render(request, "story6/kegiatan.html", context)


def add_kegiatan_view(request):
    form = TambahKegiatanForm()
    if request.method == "POST":
        form = TambahKegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("story6:all-kegiatan"))
    context = {
        "kegiatan_form": form
    }
    return render(request, "story6/kegiatan-add.html", context)


def kegiatan_add_pendaftar_post(request, id):
    add_member_form = TambahPendaftarForm(request.POST)
    if add_member_form.is_valid():
        add_member_form.save()
    kegiatan_requested = get_object_or_404(Kegiatan, pk=id)
    if add_member_form.is_valid():
        add_member_form = TambahPendaftarForm(
            initial={"kegiatan": kegiatan_requested})
    context = {
        "kegiatan_requested": kegiatan_requested,
        "add_member_form": add_member_form
    }
    return render(request, "story6/kegiatan-detail.html", context)


def kegiatan_delete_pendaftar(request, id):
    try:
        id_pendaftar = request.POST.get("id")
        Pendaftar.objects.get(pk=id_pendaftar).delete()
    finally:
        kegiatan_requested = get_object_or_404(Kegiatan, pk=id)
        add_member_form = TambahPendaftarForm(
            initial={"kegiatan": kegiatan_requested})
        context = {
            "kegiatan_requested": kegiatan_requested,
            "add_member_form": add_member_form
        }
        return render(request, "story6/kegiatan-detail.html", context)


def kegiatan_detail_view(request, id):
    if request.method == "POST":
        return kegiatan_add_pendaftar_post(request, id)

    kegiatan_requested = get_object_or_404(Kegiatan, pk=id)
    add_member_form = TambahPendaftarForm(
        initial={"kegiatan": kegiatan_requested})
    context = {
        "kegiatan_requested": kegiatan_requested,
        "add_member_form": add_member_form
    }
    return render(request, "story6/kegiatan-detail.html", context)

timey/views.py
import datetime
from django.shortcuts import render

# Create your views here.


def time(request, offset=0):
    t = datetime.datetime.now()
    t = t + datetime.timedelta(hours=offset+7)
    return render(request, "timey/time.html", {"time": t, "oft": offset})

story3/templates/index.html
{% extends "base.html" %} {% block title %} Home | Eko J. Salim {% endblock %}
{% block content %} {% load static%}
<div>
  <div class="header slow fadeIn animated" id="headtitle">
    <h1 class="title"><strong>EKO JULIANTO SALIM</strong></h1>
    <p class="subtitle">Student, Developer, and Data Science Enthusiast</p>
    <div class="links">
      <a class="link" href="https://morphism.id/projects/" title="Projects"
        >Projects</a
      >
      <a class="link" href="https://blog.morphism.id" title="Blog">Blog</a>
      <a
        class="link"
        href="https://github.com/ekojsalim"
        title="GitHub (@ekojsalim)"
        >GitHub</a
      >
      <a
        class="link"
        href="mailto:eko@morphism.id"
        title="Email (eko@morphism.id)"
        >Email</a
      >
    </div>
  </div>
</div>
<div id="container" class="hidden slow">
  <canvas></canvas>
</div>
{% endblock %} {% block js %}
<script id="vertexShader" type="x-shader/x-vertex">
  //
  // GLSL textureless classic 3D noise "cnoise",
  // with an RSL-style periodic variant "pnoise".
  // Author:  Stefan Gustavson (stefan.gustavson@liu.se)
  // Version: 2011-10-11
  //
  // Many thanks to Ian McEwan of Ashima Arts for the
  // ideas for permutation and gradient selection.
  //
  // Copyright (c) 2011 Stefan Gustavson. All rights reserved.
  // Distributed under the MIT license. See LICENSE file.
  // https://github.com/ashima/webgl-noise
  //

  vec3 mod289(vec3 x)
  {
    return x - floor(x * (1.0 / 289.0)) * 289.0;
  }

  vec4 mod289(vec4 x)
  {
    return x - floor(x * (1.0 / 289.0)) * 289.0;
  }

  vec4 permute(vec4 x)
  {
    return mod289(((x*34.0)+1.0)*x);
  }

  vec4 taylorInvSqrt(vec4 r)
  {
    return 1.79284291400159 - 0.85373472095314 * r;
  }

  vec3 fade(vec3 t) {
    return t*t*t*(t*(t*6.0-15.0)+10.0);
  }

  // Classic Perlin noise
  float cnoise(vec3 P)
  {
    vec3 Pi0 = floor(P); // Integer part for indexing
    vec3 Pi1 = Pi0 + vec3(1.0); // Integer part + 1
    Pi0 = mod289(Pi0);
    Pi1 = mod289(Pi1);
    vec3 Pf0 = fract(P); // Fractional part for interpolation
    vec3 Pf1 = Pf0 - vec3(1.0); // Fractional part - 1.0
    vec4 ix = vec4(Pi0.x, Pi1.x, Pi0.x, Pi1.x);
    vec4 iy = vec4(Pi0.yy, Pi1.yy);
    vec4 iz0 = Pi0.zzzz;
    vec4 iz1 = Pi1.zzzz;

    vec4 ixy = permute(permute(ix) + iy);
    vec4 ixy0 = permute(ixy + iz0);
    vec4 ixy1 = permute(ixy + iz1);

    vec4 gx0 = ixy0 * (1.0 / 7.0);
    vec4 gy0 = fract(floor(gx0) * (1.0 / 7.0)) - 0.5;
    gx0 = fract(gx0);
    vec4 gz0 = vec4(0.5) - abs(gx0) - abs(gy0);
    vec4 sz0 = step(gz0, vec4(0.0));
    gx0 -= sz0 * (step(0.0, gx0) - 0.5);
    gy0 -= sz0 * (step(0.0, gy0) - 0.5);

    vec4 gx1 = ixy1 * (1.0 / 7.0);
    vec4 gy1 = fract(floor(gx1) * (1.0 / 7.0)) - 0.5;
    gx1 = fract(gx1);
    vec4 gz1 = vec4(0.5) - abs(gx1) - abs(gy1);
    vec4 sz1 = step(gz1, vec4(0.0));
    gx1 -= sz1 * (step(0.0, gx1) - 0.5);
    gy1 -= sz1 * (step(0.0, gy1) - 0.5);

    vec3 g000 = vec3(gx0.x,gy0.x,gz0.x);
    vec3 g100 = vec3(gx0.y,gy0.y,gz0.y);
    vec3 g010 = vec3(gx0.z,gy0.z,gz0.z);
    vec3 g110 = vec3(gx0.w,gy0.w,gz0.w);
    vec3 g001 = vec3(gx1.x,gy1.x,gz1.x);
    vec3 g101 = vec3(gx1.y,gy1.y,gz1.y);
    vec3 g011 = vec3(gx1.z,gy1.z,gz1.z);
    vec3 g111 = vec3(gx1.w,gy1.w,gz1.w);

    vec4 norm0 = taylorInvSqrt(vec4(dot(g000, g000), dot(g010, g010), dot(g100, g100), dot(g110, g110)));
    g000 *= norm0.x;
    g010 *= norm0.y;
    g100 *= norm0.z;
    g110 *= norm0.w;
    vec4 norm1 = taylorInvSqrt(vec4(dot(g001, g001), dot(g011, g011), dot(g101, g101), dot(g111, g111)));
    g001 *= norm1.x;
    g011 *= norm1.y;
    g101 *= norm1.z;
    g111 *= norm1.w;

    float n000 = dot(g000, Pf0);
    float n100 = dot(g100, vec3(Pf1.x, Pf0.yz));
    float n010 = dot(g010, vec3(Pf0.x, Pf1.y, Pf0.z));
    float n110 = dot(g110, vec3(Pf1.xy, Pf0.z));
    float n001 = dot(g001, vec3(Pf0.xy, Pf1.z));
    float n101 = dot(g101, vec3(Pf1.x, Pf0.y, Pf1.z));
    float n011 = dot(g011, vec3(Pf0.x, Pf1.yz));
    float n111 = dot(g111, Pf1);

    vec3 fade_xyz = fade(Pf0);
    vec4 n_z = mix(vec4(n000, n100, n010, n110), vec4(n001, n101, n011, n111), fade_xyz.z);
    vec2 n_yz = mix(n_z.xy, n_z.zw, fade_xyz.y);
    float n_xyz = mix(n_yz.x, n_yz.y, fade_xyz.x);
    return 2.2 * n_xyz;
  }

  // Classic Perlin noise, periodic variant
  float pnoise(vec3 P, vec3 rep)
  {
    vec3 Pi0 = mod(floor(P), rep); // Integer part, modulo period
    vec3 Pi1 = mod(Pi0 + vec3(1.0), rep); // Integer part + 1, mod period
    Pi0 = mod289(Pi0);
    Pi1 = mod289(Pi1);
    vec3 Pf0 = fract(P); // Fractional part for interpolation
    vec3 Pf1 = Pf0 - vec3(1.0); // Fractional part - 1.0
    vec4 ix = vec4(Pi0.x, Pi1.x, Pi0.x, Pi1.x);
    vec4 iy = vec4(Pi0.yy, Pi1.yy);
    vec4 iz0 = Pi0.zzzz;
    vec4 iz1 = Pi1.zzzz;

    vec4 ixy = permute(permute(ix) + iy);
    vec4 ixy0 = permute(ixy + iz0);
    vec4 ixy1 = permute(ixy + iz1);

    vec4 gx0 = ixy0 * (1.0 / 7.0);
    vec4 gy0 = fract(floor(gx0) * (1.0 / 7.0)) - 0.5;
    gx0 = fract(gx0);
    vec4 gz0 = vec4(0.5) - abs(gx0) - abs(gy0);
    vec4 sz0 = step(gz0, vec4(0.0));
    gx0 -= sz0 * (step(0.0, gx0) - 0.5);
    gy0 -= sz0 * (step(0.0, gy0) - 0.5);

    vec4 gx1 = ixy1 * (1.0 / 7.0);
    vec4 gy1 = fract(floor(gx1) * (1.0 / 7.0)) - 0.5;
    gx1 = fract(gx1);
    vec4 gz1 = vec4(0.5) - abs(gx1) - abs(gy1);
    vec4 sz1 = step(gz1, vec4(0.0));
    gx1 -= sz1 * (step(0.0, gx1) - 0.5);
    gy1 -= sz1 * (step(0.0, gy1) - 0.5);

    vec3 g000 = vec3(gx0.x,gy0.x,gz0.x);
    vec3 g100 = vec3(gx0.y,gy0.y,gz0.y);
    vec3 g010 = vec3(gx0.z,gy0.z,gz0.z);
    vec3 g110 = vec3(gx0.w,gy0.w,gz0.w);
    vec3 g001 = vec3(gx1.x,gy1.x,gz1.x);
    vec3 g101 = vec3(gx1.y,gy1.y,gz1.y);
    vec3 g011 = vec3(gx1.z,gy1.z,gz1.z);
    vec3 g111 = vec3(gx1.w,gy1.w,gz1.w);

    vec4 norm0 = taylorInvSqrt(vec4(dot(g000, g000), dot(g010, g010), dot(g100, g100), dot(g110, g110)));
    g000 *= norm0.x;
    g010 *= norm0.y;
    g100 *= norm0.z;
    g110 *= norm0.w;
    vec4 norm1 = taylorInvSqrt(vec4(dot(g001, g001), dot(g011, g011), dot(g101, g101), dot(g111, g111)));
    g001 *= norm1.x;
    g011 *= norm1.y;
    g101 *= norm1.z;
    g111 *= norm1.w;

    float n000 = dot(g000, Pf0);
    float n100 = dot(g100, vec3(Pf1.x, Pf0.yz));
    float n010 = dot(g010, vec3(Pf0.x, Pf1.y, Pf0.z));
    float n110 = dot(g110, vec3(Pf1.xy, Pf0.z));
    float n001 = dot(g001, vec3(Pf0.xy, Pf1.z));
    float n101 = dot(g101, vec3(Pf1.x, Pf0.y, Pf1.z));
    float n011 = dot(g011, vec3(Pf0.x, Pf1.yz));
    float n111 = dot(g111, Pf1);

    vec3 fade_xyz = fade(Pf0);
    vec4 n_z = mix(vec4(n000, n100, n010, n110), vec4(n001, n101, n011, n111), fade_xyz.z);
    vec2 n_yz = mix(n_z.xy, n_z.zw, fade_xyz.y);
    float n_xyz = mix(n_yz.x, n_yz.y, fade_xyz.x);
    return 1.5 * n_xyz;
  }

  // Turbulence By Jaume Sanchez => https://codepen.io/spite/

  varying vec2 vUv;
  varying float noise;
  varying float qnoise;
  varying float displacement;

  uniform float time;
  uniform float pointscale;
  uniform float decay;
  uniform float complex;
  uniform float waves;
  uniform float eqcolor;
  uniform bool fragment;

  float turbulence( vec3 p) {
    float t = - 0.1;
    for (float f = 1.0 ; f <= 3.0 ; f++ ){
      float power = pow( 2.0, f );
      t += abs( pnoise( vec3( power * p ), vec3( 10.0, 10.0, 10.0 ) ) / power );
    }
    return t;
  }

  void main() {

    vUv = uv;

    noise = (1.0 *  - waves) * turbulence( decay * abs(normal + time));
    qnoise = (2.0 *  - eqcolor) * turbulence( decay * abs(normal + time));
    float b = pnoise( complex * (position) + vec3( 1.0 * time ), vec3( 100.0 ) );

    if (fragment == true) {
      displacement = - sin(noise) + normalize(b * 0.5);
    } else {
      displacement = - sin(noise) + cos(b * 0.5);
    }

    vec3 newPosition = (position) + (normal * displacement);
    gl_Position = (projectionMatrix * modelViewMatrix) * vec4( newPosition, 1.0 );
    gl_PointSize = (pointscale);
    //gl_ClipDistance[0];

  }
</script>
<script id="fragmentShader" type="x-shader/x-vertex">
  varying float qnoise;

  uniform float time;
  uniform bool redhell;

  void main() {
    float r, g, b;


    if (!redhell == true) {
      r = cos(qnoise + 0.5);
      g = cos(qnoise - 0.5);
      b = 0.0;
    } else {
      r = cos(qnoise + 0.5);
      g = cos(qnoise - 0.5);
      b = abs(qnoise);
    }
    gl_FragColor = vec4(r, g, b, 1.0);
  }
</script>
<script
  async
  src="https://cdnjs.cloudflare.com/ajax/libs/three.js/89/three.min.js"
></script>

<script async src="{% static 'script.js' %}"></script>
{% endblock %}

story5/templates/story5/addcourse.html
<!-- prettier-ignore -->
{% extends "base.html" %}
<!-- prettier-ignore -->
{% block title %} Add Course | Eko J. Salim {%endblock %} {% block css %}
<style>
  body {
    background-color: white;
    color: black;
  }
</style>
{% endblock %}
<!-- prettier-ignore -->
{% block content %} {% load static%} {% load crispy_forms_tags %}
<div class="container container-fluid my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Add Course</h3>
          <form action="{% url 'add-course'%}" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-success">Add Course</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center my-4">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Delete Course</h3>
          <form action="{% url 'delete-course'%}" method="POST">
            {% csrf_token %} {{ delete_form|crispy }}
            <button type="submit" class="btn btn-success">Delete Course</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- prettier-ignore -->
{% endblock %}

story6/templates/story6/kegiatan-add.html
<!-- prettier-ignore -->
{% extends "base.html" %}
<!-- prettier-ignore -->
{% block title %} Kegiatan | Eko J. Salim {%endblock %} {% block css %}
<style>
  body {
    background-color: white;
    color: black;
  }
</style>
{% endblock %}
<!-- prettier-ignore -->
{% block content %} {% load static%} {% load crispy_forms_tags %}
<div class="container container-fluid my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Tambah Kegiatan</h3>
          <form action="{% url 'story6:add-kegiatan' %}" method="POST">
            {% csrf_token %} {{ kegiatan_form|crispy }}
            <button type="submit" class="btn btn-primary">Tambah</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- prettier-ignore -->
  {% endblock %}
</div>

story6/templates/story6/kegiatan-detail.html
<!-- prettier-ignore -->
{% extends "base.html" %}
<!-- prettier-ignore -->
{% block title %} Kegiatan | Eko J. Salim {%endblock %} {% block css %}
<style>
  body {
    background-color: white;
    color: black;
  }
</style>
{% endblock %}
<!-- prettier-ignore -->
{% block content %} {% load static%} {% load crispy_forms_tags %}
<div class="container container-fluid my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">{{kegiatan_requested.nama}}</h3>
          <p>{{kegiatan_requested.deskripsi}}</p>
          <div class="list-group">
            <h4>Pendaftar</h4>
            {% if kegiatan_requested.pendaftar.all|length == 0 %}
            <p>
              Tidak ada pendaftar!
            </p>
            {% endif %}
            <div class="d-flex flex-column align-items-start mx-auto">
              {% for pendaftar in kegiatan_requested.pendaftar.all %}
              <form
                action="{% url 'story6:pendaftar-delete' id=kegiatan_requested.id %}"
                method="POST"
              >
                {% csrf_token %}
                <div>
                  <input type="hidden" name="id" value="{{pendaftar.id}}" />
                  <input
                    type="submit"
                    class="btn btn-danger mr-2 my-1"
                    value="x"
                  />
                  {{ pendaftar.nama }}
                </div>
              </form>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <div class="card mt-3">
        <div class="card-body">
          <h3 class="card-title">Daftar Kegiatan Ini</h3>
          <form
            action="{% url 'story6:kegiatan-detail' id=kegiatan_requested.id %}"
            method="POST"
          >
            {% csrf_token %} {{ add_member_form|crispy }}
            <button type="submit" class="btn btn-primary">Daftar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- prettier-ignore -->
  {% endblock %}
</div>

story6/templates/story6/kegiatan.html
<!-- prettier-ignore -->
{% extends "base.html" %}
<!-- prettier-ignore -->
{% block title %} Kegiatan | Eko J. Salim {%endblock %} {% block css %}
<style>
  body {
    background-color: white;
    color: black;
  }
</style>
{% endblock %}
<!-- prettier-ignore -->
{% block content %} {% load static%} {% load crispy_forms_tags %}
<div class="container container-fluid my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Kegiatan List</h3>
          <div class="list-group">
            {% for kegiatan in kegiatan_all %}
            <a
              href="{% url 'story6:kegiatan-detail' id=kegiatan.id %}"
              class="list-group-item list-group-item-action"
            >
              {{ kegiatan.nama }} |
              <small class="text-muted">{{ kegiatan.tanggal_dibuat }}</small>
            </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- prettier-ignore -->
  {% endblock %}
</div>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light">
  <a class="navbar-brand" href="#">Eko J. Salim</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'projects' %}">Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">Story 1</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'time' 0 %}">Time</a>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Story 5
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'all-course' %}">All Courses</a>
          <a class="dropdown-item" href="{% url 'add-course' %}"
            >Add/Delete Courses</a
          >
        </div>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
        >
          Story 6
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'story6:all-kegiatan' %}"
            >Semua Kegiatan</a
          >
          <a class="dropdown-item" href="{% url 'story6:add-kegiatan' %}"
            >Tambah Kegiatan</a
          >
        </div>
      </li>
    </ul>
  </div>
</nav>

timey/templates/timey/time.html
{% extends "base.html" %} {% block content %}
<div>Current time with offset {{ oft }}: {{ time|date:"D, d M Y H:m:s" }}</div>
{% endblock %} {% block title %}Time {% endblock %}